PREFIX ns: <https://www.vascomap.com/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wd: <https://www.wikidata.org/wiki/>

# QUERY PARA VER EL RDF
    SELECT distinct ?x ?y ?z
    WHERE {
        ?x ?y ?z.
    }

# QUERY PARA VER TODAS LAS OBSERVACIONES DE DOTPOL POR MUNICIPIOS
	SELECT distinct ?obs ?value ?id ?mun ?munLink 
    WHERE {
        ?obs a ns:DotPol;
            ns:value ?value;
            ns:id ?id;
            ns:takesPlaceInMun ?mun.
        ?mun owl:sameAs ?munLink.
    }

# QUERY PARA VER TODAS LAS OBSERVACIONES DE INDDEL POR PROVINCIAS
	SELECT distinct ?obs ?value ?id ?prov ?provLink
    WHERE {
        ?obs a ns:IndDel;
            ns:value ?value;
            ns:id ?id;
            ns:takesPlaceInProv ?prov.
        ?prov owl:sameAs ?provLink.
    }
	
# QUERY PARA VER TODAS LAS OBSERVACIONES DE SEGZON
    SELECT distinct ?obs ?value ?id ?prov ?provLink
    WHERE {
        ?obs a ns:SegZon;
            ns:value ?value;
            ns:id ?id;
            ns:takesPlaceInProv ?prov.
        ?prov owl:sameAs ?provLink.
    }
	
# QUERY PARA VER TODAS LAS OBSERVACIONES DE INFPEN
    SELECT distinct ?obs ?value ?id ?prov ?provLink
    WHERE {
        ?obs a ns:InfPen;
            ns:value ?value;
            ns:id ?id;
            ns:takesPlaceInProv ?prov.
        ?prov owl:sameAs ?provLink.
    }

# QUERY PARA VER TODOS LOS DATOS DE LAS PROVINCIAS
    SELECT distinct ?prov ?name ?link ?mun
    WHERE {
        ?prov a ns:Province;
            ns:name ?name;
            ns:has ?mun;
            owl:sameAs ?link.
    }

# QUERY PARA VER TODOS LOS DATOS DE LOS MUNICIPIOS
    SELECT distinct ?mun ?name ?code ?prov ?link
    WHERE {
        ?mun a ns:Municipality;
            ns:name ?name;
            ns:code ?code;
            ns:belongsTo ?prov;
            owl:sameAs ?link.
    }
	
# QUERY PARA OBTENER LOS DATOS RELACIONADOS CON LA OBSERVACIÓN DEL ÍNDICE DE DOTACIÓN POLICIAL QUE HAY EN ABADIÑO
    SELECT distinct ?obs ?id ?value ?mun ?prov ?provLink
    WHERE {
        ?obs a ns:DotPol;
            ns:id ?id;
            ns:value ?value;
            ns:takesPlaceInMun ?mun.
        ?mun owl:sameAs wd:Q744893;
            ns:belongsTo ?prov.
        ?prov owl:sameAs ?provLink.
    }
	
# QUERY PARA OBTENER LOS MUNICIPIOS CON UN ÍNDICE DE DELITOS MAYOR A 50
    SELECT distinct ?obs ?value ?mun ?link
    WHERE {
        ?obs a ns:IndDel;
            ns:value ?value;
            ns:takesPlaceInMun ?mun.
        FILTER(?value > 50).
        ?mun owl:sameAs ?link.
    }

# QUERY PARA OBTENER LOS MUNICIPIOS QUE PERTENECEN A BISCAY
    SELECT distinct ?mun ?munName ?code ?munLink
    WHERE {
        ?prov a ns:Province;
            ns:name "Biscay";
            ns:has ?mun.
        ?mun a ns:Municipality;
            ns:name ?munName;
            ns:code ?code;
            owl:sameAs ?munLink.
    }