# -*- coding: utf-8 -*-
"""Copia de Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p1nwbCPbiXfAaTztPaOyKjasQ1_gzwEd

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS, FOAF
from rdflib.plugins.sparql import prepareQuery
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns = Namespace("http://somewhere#")
q1 = prepareQuery('''
  SELECT ?subclass
  WHERE {
    ?subclass rdfs:subClassOf* <http://somewhere#LivingThing>.
  }
  ''',
  initNs = { "vcard": VCARD}
)
"""
for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
  print(s)
"""
# Visualize the results
for r in g.query(q1):
  print(r.subclass)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
ns =  Namespace("http://somewhere#")
q2 = prepareQuery('''
  SELECT ?sujeto
  WHERE {
    ?sujeto rdfs:subClassOf* <http://somewhere#Person>.
  }
  ''',
  initNs = { "vcard": VCARD}
)

# Visualize the results
for r in g.query(q2):
  print(r.sujeto)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
#FOAF = Namespace("http://xmlns.com/foaf/0.1/")
q3 = prepareQuery("""
SELECT ?individual ?property ?value ?class
WHERE {
    ?individual a ?class .
    FILTER (?class = ns:Person || ?class = ns:Animal)
    ?individual ?property ?value .
}
""", initNs={"ns": ns})


for r in g.query(q3):
    print("Individual:", r.individual)
    print("Property:", r.property)
    print("Value:", r.value)
    print("Class:", r["class"])
    print("\n")

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
q4 = '''
  SELECT ?nombre
  WHERE {
    ?nombre foaf:knows ns:RockySmith.
  }
  '''

# Visualize the results

for r in g.query(q4):
  print(r)
print("-------------------------------------")
for s,p,o in g.triples((None, FOAF.knows, ns.RockySmith)):
  print(s,p,o)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
q5 = """
    SELECT ?sujeto
    WHERE {
        ?sujeto foaf:knows ?other1 .
        ?sujeto foaf:knows ?other2 .
        FILTER (?other1 != ?other2)
    }
"""

# Visualize the results
for r in g.query(q5):
  print(r.sujeto)