# 1. Dado el código postal 28024 devolver los nombres de los polideportivos de tipo centro deportivo y los id de los aparcabicis
SELECT ?nombre_pol ?id_apar WHERE {
	?polideportivo pol:Tipo 'Centro Deportivo'.
	?loc ubi:Codigo-Postal '28024'.
	?polideportivo ubi:se_encuentra_en ?loc.
            ?polideportivo pol:Nombre ?nombre_pol .
	?aparcabicis ubi:se_encuentra_en ?loc.
             ?aparcabicis apar:ID ?id_apar .
}


# 2. Devolver todos los pk de los polideportivos y los id de aparcabicis de modelo "MU-51" que se encuentren en el distrito "VILLA DE VALLECAS"

SELECT ?pk_pol ?id_apar WHERE {
	?loc ubi:Distrito 'VILLA DE VALLECAS'.
	?polideportivo ubi:se_encuentra_en ?loc.
             ?polideportivo pol:PK ?pk_pol.
	?aparcabicis ubi:se_encuentra_en ?loc.
             ?aparcabicis apar:Modelo 'MU-51'.
             ?aparcabicis apar:ID ?id_apar.
}


# 3. Mostrar el estado de las aparcabicis:

SELECT DISTINCT ?Estado
WHERE
    {
    ?aparcabicis apar:Estado ?Estado
    }
LIMIT 20


#4. Devuelve los id de los aparcabicis que se pueden encontrar en Aluche:
SELECT ?id
WHERE {
    ?loc ubi:Barrio 'Aluche'.
    ?aparcabicis ubi:se_encuentra_en ?loc.
  ?aparcabicis apar:ID ?id.
}


# 5. Dado la fecha de instalacion 2021-09-21 de los aparcabicis devolver el ID, el barrio y el estado de los aparcabicis
SELECT ?id ?barrio ?Estado
WHERE {
	?aparcabicis apar:Fecha-instalacion '2021-09-21'.
  ?aparcabicis apar:ID ?id.
  ?aparcabicis ubi:Barrio ?barrio.
  ?aparcabicis apar:Estado ?Estado.
}
LIMIT 20


# 6. Dado un distrito (CHAMARTIN) y filtrando por el nombre del barrio (NUEVA ESPAÑA) devolver el nombre del polideportivo y el ID del aparcabicis
SELECT ?nombre ?id
WHERE {
  ?loc ubi:Distrito 'CHAMARTIN'.
  ?loc ubi:Barrio ?barrio.
  FILTER (?barrio == 'NUEVA ESPAÑA')
	?polideportivo ubi:se_encuentra_en ?barrio.
	?aparcabicis ubi:se_encuentra_en ?barrio.
  ?aparcabicis apar:ID ?id.
  ?polideportivo pol:Nombre ?nombre.
}
LIMIT 10
