@prefix base: <http://deportesMadrid/ontology#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

# 1. Dado el código postal 28024 devolver los nombres de los polideportivos de tipo centro deportivo y los id de los aparcabicis

SELECT ?nombre_pol ?id_apar
WHERE {
	?polideportivo base:Tipo 'Centro Deportivo'.
	?loc base:Codigo-Postal '28024'.
	?polideportivo base:se_encuentra_en ?loc.
    	?polideportivo base:Nombre ?nombre_pol .
	?aparcabicis base:se_encuentra_en ?loc.
    	?aparcabicis base:ID ?id_apar.
}


# 2. Devolver todos los pk de los polideportivos y los id de aparcabicis de modelo "MU-51" que se encuentren en el distrito "VILLA DE VALLECAS"

SELECT ?pk_pol ?id_apar
WHERE {
	?loc base:Distrito 'VILLA DE VALLECAS'.
	?polideportivo base:se_encuentra_en ?loc.
    	?polideportivo base:PK ?pk_pol.
	?aparcabicis base:se_encuentra_en ?loc.
    	?aparcabicis base:Modelo 'MU-51'.
    	?aparcabicis base:ID ?id_apar.
}


# 3. Mostrar el estado de los aparcabicis que su clase vial no sea una avenida.

SELECT DISTINCT ?estado
WHERE
    {
    ?aparcabicis base:Clase-vial ?clase.
  FILTER (?clase != "AVENIDA")
    ?aparcabicis base:Estado ?estado.
    }
LIMIT 20


#4. Devuelve los id de los aparcabicis que se pueden encontrar en una calle del barrio Aluche.

SELECT ?id_apar
WHERE {
    ?loc base:se_encuentra_en 'ALUCHE'
    ?aparcabicis base:se_encuentra_en ?loc.
    ?aparcabicis base:Clase-vial 'CALLE'.
    ?aparcabicis base:ID ?id_apar.


# 5. Dado la fecha de instalacion 2021-09-21 de los aparcabicis devolver el ID, el barrio y el estado de los aparcabicis

SELECT ?id ?barrio ?estado
WHERE {
	?aparcabicis base:Fecha-instalacion '2021-09-21'.
  	?aparcabicis base:ID ?id.
 	?aparcabicis base:Barrio ?barrio.
  	?aparcabicis base:Estado ?estado.
}
LIMIT 20


# 6. Dado un distrito (CHAMARTIN) y filtrando por el nombre del barrio (NUEVA ESPAÑA) devolver el nombre del polideportivo y el ID del aparcabicis

SELECT ?nombre ?id
WHERE {
  	?loc1 base:Distrito 'CHAMARTIN'.
  	?loc2 base:Barrio ?barrio.
  FILTER (?barrio == 'NUEVA ESPAÑA')
	?polideportivo base:se_encuentra_en ?barrio.
	?aparcabicis base:se_encuentra_en ?barrio.
 	?aparcabicis base:ID ?id.
  	?polideportivo base:Nombre ?nombre.
}
LIMIT 10
