# -*- coding: utf-8 -*-
"""trask07corr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VsYKn9L_0kjon4D8PcATQMtzOuQ-bK3

# **Task07.ipynb**

Daniel Llopis, 21C033

Primero leemos el grafo
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"


from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://somewhere#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")

"""7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL"""

# TO DO
from rdflib.plugins.sparql import prepareQuery

livingThing_query = prepareQuery('''
SELECT distinct ?subClass
WHERE {
    ?subClass rdfs:subClassOf* ns:LivingThing
}
''',
initNs = { "rdfs": RDFS, "ns": ns}
)
# Visualize the results

for r in g.query(livingThing_query):
  print(r)


def fun_subclasses(g,class_name):
  subclasses = set()
  for s,p,o in g.triples((None,RDF.type,RDFS.Class)):
    if (s,RDFS.subClassOf,class_name) in g:
      subclasses.add(s)
      subclasses.update(fun_subclasses(g,s))
  return subclasses
subclasses_lt = fun_subclasses(g,ns.LivingThing)
for subclass in subclasses_lt:
  print(subclass)

""" 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)"""

# TO DO

person_query = prepareQuery('''
SELECT ?individual
WHERE {
    ?individual rdf:type/rdfs:subClassOf* ns:Person .
}
''',
initNs = { "rdf": RDF, "rdfs": RDFS, "ns": ns}
)

# Visualize the results

for r in g.query(person_query):
  print(r)


rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")

print("RDFLib")
for s,p,o in g.triples((None, RDF.type, ns.Person)):
  print(s)
for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
  for s1,p1,o1 in g.triples((None, RDF.type, s)):
    print(s1)

"""7.3 List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person"""

# TO DO

# Create a set to store the individuals of "Person" or "Animal"
individuals = set()

# Create a set of classes to include "Person" and "Animal"
classes_to_include = {ns.Person, ns.Animal}

for subject, predicate, object_ in g.triples((None, RDF.type, None)):
    if object_ in classes_to_include:
        individuals.add(subject)

for individual in individuals:
    print("Individual:", individual)
    for s, p, o in g.triples((individual, None, None)):
        print(f" Property: {p}, Value: {o}")

q3 = prepareQuery('''
    SELECT distinct ?individual ?property ?x
    WHERE {
        {
          ?individual a ns:Person.
        }
        UNION
        {
          ?individual a ns:Animal.
        }
        ?individual ?property ?x
    }
    ''',
    initNs = {"rdfs": rdfs, "rdf": rdf, "ns": ns}
)

for r in g.query(q3):
  print(r)

""" 7.4: List the name of the persons who know Rocky"""

from rdflib import FOAF
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")


for s, p, o in g.triples((None, FOAF.knows, ns.RockySmith)):
  print(s)


q4 = prepareQuery('''
  SELECT ?individual ?name
  WHERE {
    ?individual FOAF:knows ns:RockySmith.
    ?individual <http://www.w3.org/2001/vcard-rdf/3.0/Given> ?name
  }
  ''',
  initNs = {"FOAF": FOAF, "VCARD": VCARD, "ns": ns}
)

for r in g.query(q4):
  print(r)

"""7.5: List the entities who know at least two other entities in the graph"""

# TO DO

query_5 = prepareQuery('''
SELECT ?entity ?relatedEntity
WHERE {
      ?entity foaf:knows ?relatedEntity .

}
GROUP BY ?entity
HAVING (COUNT(DISTINCT ?relatedEntity) >= 2)

''',
initNs = { "foaf": FOAF , "ns" : ns, "vcard": VCARD}
)

# Visualize the results

for r in g.query(query_5):
     print(r.entity)