# -*- coding: utf-8 -*-
"""Copia de Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/129YOR8nV8JxkWGkL3Sq4EYa1-P9xPml3

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO

ns = Namespace("http://somewhere#")
qres = g.query(
            """SELECT DISTINCT ?x
               WHERE {
                  ?x rdfs:subClassOf ns:LivingThing
               }""", initNs = {"rdfs": RDFS, "ns": ns})
for r in qres:
    print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
qres = g.query(
        """SELECT DISTINCT ?x
           WHERE
           {{
            ?x rdf:type ns:Person
           }
           UNION
           {
            ?x rdfs:subClassOf ns:Person.
            ?b rdf:type ?x
           }}""",
         initNs = {"rdfs": RDFS, "ns": ns, "rdf": RDF})

for r in qres:
    print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
qres = g.query(
        """SELECT DISTINCT ?x ?p
           WHERE
           {{
            ?x rdf:type ns:Person.
            ?x ?p ?b
           }
           UNION
           {
            ?x rdf:type ns:Animal.
            ?x ?p ?b
           }}""",
         initNs = {"ns": ns, "rdf": RDF})

for r in qres:
    print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
from rdflib import FOAF

qres = g.query(
    """SELECT DISTINCT ?x ?p
       WHERE {
          {
            ?x rdf:type ns:Person.
            ?x foaf:knows ?p.
            ?p foaf:name "Rocky".
          }
          UNION
          {
            ?x rdf:type ?p.
            ?p rdf:type ns:Person.
            ?x foaf:knows ?p.
            ?p foaf:name "Rocky".
          }
       }
    """
)

for row in qres:
    print(f"Person: {row.x}, Knows: {row.p}")

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results