# -*- coding: utf-8 -*-
"""AlbaLozano_22C025

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Jr0detRw0tI8dNO9DCwRjiv4uIpxhtc

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
# Visualize the results

#for r in g.query(q1):
#  print(r)
q1 = """
    SELECT distinct ?subClass
    WHERE {
        ?subClass rdfs:subClassOf ns:LivingThing .
    }
"""

for r in g.query(q1):
    print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
# Visualize the results
q2 = """
    SELECT distinct ?person
    WHERE {
        ?person rdfs:subClassOf* ?personType .
        ?personType rdfs:subClassOf* ns:Person .
    }
"""

for r in g.query(q2):
    print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

ns = Namespace("http://somewhere#")

# Construct a SPARQL query to find individuals of "Person" or "Animal" with their properties
query = """
    SELECT ?individual ?class ?property ?value
    WHERE {
        ?individual a ?class .
        ?class rdfs:subClassOf* ns:LivingThing .
        FILTER (?class = ns:Person || ?class = ns:Animal)
        ?individual ?property ?value .
    }
"""
for r in g.query(query):
    print(r)



"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
# Visualize the results
# TO DO
# Visualize the results

q4 = """
SELECT ?personName
WHERE {
    ?person a ns:Person ; ns:knows
    ?otherPerson .
    ?otherPerson ns:name "Rocky" .
    ?person ns:name ?personName .
    ?personName foaf:knows ns:RockySmith.
}
"""
for row in g.query(q4):
    print(row)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results


VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
from rdflib.plugins.sparql import prepareQuery
from rdflib import FOAF
g.add((ns.A, FOAF.knows, ns.B))

# Define a SPARQL query to find entities that know at least two other entities
q5 = prepareQuery("""
    SELECT ?entity ?relatedE
    WHERE {
        ?entity foaf:knows ?relatedE .
    }
    GROUP BY ?entity
    HAVING (COUNT(DISTINCT ?relatedE) >= 2)
""", initNs={"foaf":FOAF,"ns": ns,"vcard":VCARD})

for r in g.query(q5):
    print(r.entity)