# -*- coding: utf-8 -*-
"""Copia de Task07.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l7ptMcKnlA0udS4ttfMVxkwjI7UOw957

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
ns = Namespace("http://somewhere#")
qres = g.query(
        """SELECT DISTINCT ?a
           WHERE {
              ?a rdfs:subClassOf ns:LivingThing
           }""", initNs = {"rdfs": RDFS, "ns": ns})

# Visualize the results
for r in qres:
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
qres = g.query(
        """SELECT DISTINCT ?a
           WHERE
           {{
            ?a rdf:type ns:Person
           }
           UNION
           {
            ?a rdfs:subClassOf ns:Person.
            ?b rdf:type ?a
           }}""",
         initNs = {"rdfs": RDFS, "ns": ns, "rdf": RDF})

# Visualize the results
for r in qres:
  print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
qres = g.query(
        """SELECT DISTINCT ?a ?p
           WHERE
           {{
            ?a rdf:type ns:Person.
            ?a ?p ?b
           }
           UNION
           {
            ?a rdf:type ns:Animal.
            ?a ?p ?b
           }}""",
         initNs = {"ns": ns, "rdf": RDF})

# Visualize the results
for r in qres:
  print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
from rdflib import FOAF

qres = g.query(
        """SELECT DISTINCT ?a
           WHERE
           {{{
            ?a rdf:type ns:Person
           }
           UNION
           {
            ?a rdfs:subClassOf ns:Person.
            ?b rdf:type ?a
           }}
           FILTER(?a foaf:knows ns:RockySmith)
           }
           """,
         initNs = {"rdfs": RDFS, "ns": ns, "rdf": RDF, "foaf": FOAF})

# Visualize the results
for r in qres:
  print(r)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results