# -*- coding: utf-8 -*-
"""Copia de Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S19yA93b5umd-N_t_KQgqXfjNZs5EwIy

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery

ns = Namespace("http://somewhere#")

q1 = prepareQuery('''
  SELECT ?x
  WHERE {
    ?x rdfs:subClassOf ns:LivingThing.
  }
  ''',
  initNs = { "rdfs": RDFS, "ns":ns}
)
for r in g.query(q1):
    print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

q1 = prepareQuery('''
  SELECT ?x
  WHERE { {
    ?subclass rdfs:subClassOf ns:Person.
    ?x a ?subclass
  }
  UNION
  {
    ?x a ns:Person.
    }
  }
  ''',
  initNs = { "rdfs": RDFS, "ns":ns}
)

for r in g.query(q1):
    print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

q1 = prepareQuery('''
  SELECT ?x ?p
  WHERE {
    {?x a ns:Person.
    ?x ?p ?y}
    UNION
    {?x a ns:Animal.
    ?x ?p ?y}
  }
  ''',
  initNs = { "rdfs": RDFS, "ns":ns}
)

for r in g.query(q1):
    print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

q1 = prepareQuery('''
  SELECT ?x
  WHERE {
    ?x <http://xmlns.com/foaf/0.1/knows> ns:RockySmith.
  }
  ''',
  initNs = { "rdfs": RDFS, "ns":ns}
)

for r in g.query(q1):
    print(r)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

q1 = prepareQuery('''
  SELECT DISTINCT ?x
  WHERE {
    ?x <http://xmlns.com/foaf/0.1/knows> ?y.
    ?x <http://xmlns.com/foaf/0.1/knows> ?z.
    FILTER(?y!=?z)
  }
  ''',
  initNs = { "rdfs": RDFS, "ns":ns}
)

for r in g.query(q1):
    print(r)