# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/blob/master/Assignment4/course_materials/notebooks/Task09.ipynb

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
print("g1")
for s1,p1,o1 in g1.triples((None, VCARD.FN, None)):
  print(s1,p1,o1)

print("g2")
for s2,p2,o2 in g2.triples((None, VCARD.FN, None)):
  print(s2,p2,o2)

from rdflib.namespace import OWL

print("g3")

for s1,p1,o1 in g1.triples((None, VCARD.FN, None)):
  for s2,p2,o2 in g2.triples((None, VCARD.FN, None)):
    if (o1==o2):
      g3.add((s1, OWL.sameAs, s2))

for (s3,p3,o3) in g3:
  print(s3,p3,o3)